global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8081']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-olap:9363']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
